name: MySensors MQTT Adapter
version: "2.0.2"
slug: ms_mqtt_adapter
description: Bridge between MySensors networks and MQTT with Home Assistant auto-discovery
url: https://github.com/aszeszo/ms-mqtt-adapter
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
image: ghcr.io/aszeszo/ms-mqtt-adapter
map:
  - addon_config:/data
ports:
  5003/tcp: 5003
  5004/tcp: 5004
  5005/tcp: 5005
  5006/tcp: 5006
ports_description:
  5003/tcp: TCP service for MySensors message replication (gateway 1)
  5004/tcp: TCP service for MySensors message replication (gateway 2)
  5005/tcp: TCP service for MySensors message replication (gateway 3)
  5006/tcp: TCP service for MySensors message replication (gateway 4)
schema: false
options:
  log_level: info
  mysensors:
    default:
      transport: ethernet
      ethernet:
        host: "192.168.1.100"
        port: 5003
      gateway:
        node_id_range:
          start: 1
          end: 254
        version_request_period: "5s"
        random_id_assignment: false
      tcp_service:
        enabled: true
        port: 5003
  mqtt:
    broker: core-mosquitto
    port: 1883
    username: ""
    password: ""
    client_id: ms-mqtt-adapter
  sync:
    enabled: true
    period: "30s"
  adapter:
    topic_prefix: ms-mqtt-adapter
    homeassistant_discovery: true
    optimistic_mode: false
    request_ack: true
