name: MySensors MQTT Adapter
version: "2.0.0"
slug: ms_mqtt_adapter
description: Bridge between MySensors networks and MQTT with Home Assistant auto-discovery
url: https://github.com/aszeszo/ms-mqtt-adapter
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
image: ghcr.io/aszeszo/ms-mqtt-adapter
map:
  - share:rw
  - ssl
  - config:rw
ports:
  5003/tcp: 5003
  5004/tcp: 5004
  5005/tcp: 5005
  5006/tcp: 5006
ports_description:
  5003/tcp: TCP service for MySensors message replication (gateway 1)
  5004/tcp: TCP service for MySensors message replication (gateway 2)
  5005/tcp: TCP service for MySensors message replication (gateway 3)
  5006/tcp: TCP service for MySensors message replication (gateway 4)
options:
  log_level: info
  mysensors:
    default:
      transport: ethernet
      ethernet:
        host: "192.168.1.100"
        port: 5003
      gateway:
        node_id_range:
          start: 1
          end: 254
        version_request_period: "5s"
        random_id_assignment: false
      tcp_service:
        enabled: true
        port: 5003
  mqtt:
    broker: core-mosquitto
    port: 1883
    username: ""
    password: ""
    client_id: ms-mqtt-adapter
  sync:
    enabled: true
    period: "30s"
  adapter:
    topic_prefix: ms-mqtt-adapter
    homeassistant_discovery: true
    optimistic_mode: false
    request_ack: true
schema:
  log_level: list(debug|info|warn|error)
  mysensors:
    match(str):
      transport: list(ethernet|rs485)
      ethernet?:
        host: str
        port: port
      rs485?:
        device: str
      gateway:
        node_id_range:
          start: int(1,254)
          end: int(1,254)
        version_request_period: str
        random_id_assignment?: bool
      tcp_service:
        enabled: bool
        port: port
  mqtt:
    broker: str
    port: port
    username: str?
    password: password?
    client_id: str
  sync:
    enabled: bool
    period: str
  adapter:
    topic_prefix: str
    homeassistant_discovery: bool
    optimistic_mode?: bool
    request_ack?: bool
  # Device configurations
  devices?:
    - name: str
      id: str
      node_id: int
      gateway?: str
      manufacturer?: str
      model?: str
      sw_version?: str
      hw_version?: str
      configuration_url?: str
      suggested_area?: str
      connections?: [str]
      via_device?: str
      relays?:
        - name: str
          id: str
          child_id: int
          initial_state?: int
          icon?: str
          device_class?: str
          entity_category?: str
          enabled_by_default?: bool
          availability_topic?: str
          payload_available?: str
          payload_not_available?: str
          payload_on?: str
          payload_off?: str
          state_on?: str
          state_off?: str
          qos?: int
          retain?: bool
          optimistic?: bool
          json_attributes_topic?: str
          state_value_template?: str
          command_template?: str
      inputs?:
        - name: str
          id: str
          child_id: int
          icon?: str
          device_class?: str
          entity_category?: str
          enabled_by_default?: bool
          availability_topic?: str
          payload_available?: str
          payload_not_available?: str
          off_delay?: int
          expire_after?: int
          qos?: int
          json_attributes_topic?: str
          value_template?: str
