name: MySensors MQTT Adapter
version: "1.0.0"
slug: ms_mqtt_adapter
description: Bridge between MySensors networks and MQTT with Home Assistant auto-discovery
url: https://github.com/aszeszo/ms-mqtt-adapter
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
image: ghcr.io/aszeszo/ms-mqtt-adapter
ports:
  5003/tcp: 5003
  5004/tcp: 5004
  5005/tcp: 5005
  5006/tcp: 5006
ports_description:
  5003/tcp: TCP service for MySensors message replication (gateway 1)
  5004/tcp: TCP service for MySensors message replication (gateway 2)
  5005/tcp: TCP service for MySensors message replication (gateway 3)
  5006/tcp: TCP service for MySensors message replication (gateway 4)
schema:
  config_yaml: str
options:
  config_yaml: |
    log_level: info  # debug, info, warn, error

    mysensors:
      default:
        ethernet:
          host: "172.30.15.1"
          # port: 5003  # Default port, can be omitted
        gateway:
          node_id_range:
            start: 1
            end: 254
          random_id_assignment: true
        # tcp_service:
        #   enabled: false  # Disabled by default
      gateway2:
        ethernet:
          host: "172.30.16.1"
          port: 5003  # Use same MySensors port (different host)
        gateway:
          node_id_range:
            start: 1
            end: 254
          random_id_assignment: true
        # tcp_service:
        #   enabled: false  # Disabled by default

    mqtt:
      broker: "core-mosquitto"
      port: 1883
      username: "nippy"
      password: "nippy"
      client_id: "ms-mqtt-adapter"

    adapter:
      topic_prefix: "ms-mqtt-adapter"
      homeassistant_discovery: true  # Enable/disable HomeAssistant auto-discovery
      optimistic: false
      request_ack: true  # Request ACK bit to encourage device echoing (default: true)
      sync:
        enabled: true
        period: "30s"

    devices:
      - name: "Relay 3 #1"
        id: "relay_3_1"
        node_id: 1
        manufacturer: "Nippy"
        model: "Nippy"
        sw_version: "1.0"
        hw_version: "1.0"
        relays:
          - name: "Relay 1"
            id: "relay_1"
            child_id: 0
            initial_state: 0  # 0=OFF, 1=ON
            icon: "hue:socket-eu"
            device_class: "switch"
          - name: "Relay 2"
            id: "relay_2"
            child_id: 1
            initial_state: 0
            icon: "hue:socket-eu"
            device_class: "switch"
          - name: "Relay 3"
            id: "relay_3"
            child_id: 2
            initial_state: 0
            icon: "hue:socket-eu"
            device_class: "switch"

      - name: "Input 6 #1"
        id: "input_6_1"
        node_id: 2
        manufacturer: "Nippy"
        model: "Nippy"
        sw_version: "1.0"
        hw_version: "1.0"
        inputs:
          - name: "Input Button 1"
            id: "input_button_1"
            child_id: 0
            icon: "hue:friends-of-hue-senic"
          - name: "Input Button 2"
            id: "input_button_2"
            child_id: 1
            icon: "hue:friends-of-hue-senic"
          - name: "Input Button 3"
            id: "input_button_3"
            child_id: 2
            icon: "hue:friends-of-hue-senic"
          - name: "Input Button 4"
            id: "input_button_4"
            child_id: 3
            icon: "hue:friends-of-hue-senic"
          - name: "Input Button 5"
            id: "input_button_5"
            child_id: 4
            icon: "hue:friends-of-hue-senic"
          - name: "Input Button 6"
            id: "input_button_6"
            child_id: 5
            icon: "hue:friends-of-hue-senic"

      - name: "Relay 3 #2"
        id: "relay_3_2"
        gateway: gateway2
        node_id: 159
        manufacturer: "Nippy"
        model: "Nippy"
        sw_version: "1.0"
        hw_version: "1.0"
        relays:
          - name: "Relay 1"
            id: "relay_1"
            child_id: 0
            initial_state: 0
            icon: "hue:socket-eu"
            device_class: "switch"
          - name: "Relay 2"
            id: "relay_2"
            child_id: 1
            initial_state: 0
            icon: "hue:socket-eu"
            device_class: "switch"
          - name: "Relay 3"
            id: "relay_3"
            child_id: 2
            initial_state: 0
            icon: "hue:socket-eu"
            device_class: "switch"
