name: MySensors MQTT Adapter
version: "2.0.2"
slug: ms_mqtt_adapter
description: Bridge between MySensors networks and MQTT with Home Assistant auto-discovery
url: https://github.com/aszeszo/ms-mqtt-adapter
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
image: ghcr.io/aszeszo/ms-mqtt-adapter
map:
  - config
ports:
  5003/tcp: 5003
  5004/tcp: 5004
  5005/tcp: 5005
  5006/tcp: 5006
ports_description:
  5003/tcp: TCP service for MySensors message replication (gateway 1)
  5004/tcp: TCP service for MySensors message replication (gateway 2)
  5005/tcp: TCP service for MySensors message replication (gateway 3)
  5006/tcp: TCP service for MySensors message replication (gateway 4)
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
